package lk.icbt.findit.entity;

public enum BusinessCategory {
    GROCERY,
    SUPERMARKET,
    RESTAURANT,
    HOTEL,
    CAFE,
    PHARMACY,
    HOSPITAL,
    ELECTRONICS,
    FASHION,
    HARDWARE,
    BOOKSHOP,
    SALON,
    BAKERY,
    PET_SHOP,
    FUEL_STATION,
    AGRICULTURE,
    WHOLESALE,
    CO_WORKING_SPACE,   
    FITNESS_CENTER,     
    ENTERTAINMENT,      
    TRAVEL_AGENCY,      
    BANKING,            
    INSURANCE,          
    BEAUTY,             
    TECH_SERVICES,      
    OTHER
}
